version: "3"
services:
  mysql:
    image: mysql
    container_name: cont_db
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - "3307:3306"
    env_file: .env
    networks:
      - cont_network

  server:
    build: ./Backend/
    container_name: cont_backend
    command: sh -c "./wait-for-it.sh mysql:3306; python3 /Backend/manage.py migrate; python /Backend/manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    env_file: .env
    networks:
      - cont_network
    depends_on:
      - mysql

  client:
    build: ./Frontend/
    container_name: frontend
    command: bash -c "npm install && npm start"
    ports:
      - 3000:3000
    networks:
      - cont_network
    depends_on:
      - server
networks:
  cont_network: