# Generated by Django 3.1.14 on 2022-02-03 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='id_slot_station',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
