# Generated by Django 3.1.14 on 2022-02-03 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0002_slot_id_slot_station'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slot',
            old_name='id_slot_station',
            new_name='id_slot',
        ),
    ]
