# Generated by Django 3.1.14 on 2022-02-03 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0004_auto_20220203_1444'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slot',
            name='slot',
        ),
    ]
