# Generated by Django 3.1.14 on 2022-02-14 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0009_auto_20220214_0848'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slot',
            old_name='bike',
            new_name='id_bike',
        ),
    ]
