# Generated by Django 3.1.14 on 2022-02-15 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0013_slot_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slot',
            old_name='name',
            new_name='slot',
        ),
    ]
