# Generated by Django 3.1.14 on 2022-02-15 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0015_auto_20220215_0836'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slot',
            name='slot',
        ),
    ]
