# Generated by Django 3.1.14 on 2022-02-15 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0016_remove_slot_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='name',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
    ]
