# Generated by Django 3.1.14 on 2022-02-17 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0028_auto_20220217_2043'),
        ('stations', '0017_slot_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='oneBike',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oneBike', to='bikes.bike'),
        ),
    ]
