# Generated by Django 3.1.14 on 2022-02-19 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0018_slot_onebike'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slot',
            old_name='id_bike',
            new_name='bike',
        ),
        migrations.RemoveField(
            model_name='slot',
            name='oneBike',
        ),
    ]
