# Generated by Django 3.1.14 on 2022-02-20 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0030_auto_20220220_1748'),
        ('stations', '0019_auto_20220219_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='bike',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='bikes.bike'),
        ),
    ]
