# Generated by Django 3.1.14 on 2022-02-15 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profile_favorites'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='rentActive',
            field=models.BooleanField(blank=True, db_index=True, default=False),
        ),
    ]
