export { default as home } from './home/home'
export { default as stations } from './stations/stations'
export { default as login } from './login/login'
export { default as register } from './register/register'
export { default as adminPanel } from './adminPanel/adminPanel'
export { default as bikes } from './adminPanel/bikes'
export { default as incidences } from './adminPanel/incidences'
export { default as profile } from './profile/profile'