# Generated by Django 3.1.14 on 2022-02-10 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profile_favorites'),
        ('stations', '0005_remove_slot_slot'),
        ('bikes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentBike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateTimeField(auto_now_add=True)),
                ('date_finish', models.DateTimeField()),
                ('bike', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rent', to='bikes.bike')),
                ('slot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rent', to='stations.slot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rent', to='profiles.profile')),
            ],
        ),
    ]
