# Generated by Django 3.1.14 on 2022-02-13 21:00

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profile_favorites'),
        ('bikes', '0004_auto_20220213_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentbike',
            name='date_start',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 13, 21, 0, 33, 715134, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='rentbike',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='profiles.profile'),
        ),
    ]
