# Generated by Django 3.1.14 on 2022-02-14 12:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0012_auto_20220214_0854'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentbike',
            name='state',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='rentbike',
            name='date_start',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 14, 12, 36, 11, 732330, tzinfo=utc)),
        ),
    ]
