# Generated by Django 3.1.14 on 2022-02-14 18:28

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0016_auto_20220214_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentbike',
            name='bike',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bikes', to='bikes.bike'),
        ),
        migrations.AlterField(
            model_name='rentbike',
            name='date_start',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 14, 18, 28, 50, 805458, tzinfo=utc)),
        ),
    ]
