# Generated by Django 3.1.14 on 2022-02-15 08:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0017_auto_20220214_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentbike',
            name='date_start',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 15, 8, 35, 8, 474743, tzinfo=utc)),
        ),
    ]
