# Generated by Django 3.1.14 on 2022-02-15 08:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0021_auto_20220215_0837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentbike',
            name='date_start',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 15, 8, 37, 56, 165749, tzinfo=utc)),
        ),
    ]
