# Generated by Django 3.1.14 on 2022-02-15 08:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0023_auto_20220215_0838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentbike',
            name='date_start',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 15, 8, 39, 54, 17422, tzinfo=utc)),
        ),
    ]
