# Generated by Django 3.1.14 on 2022-02-15 12:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0026_auto_20220215_0846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentbike',
            name='date_start',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 15, 12, 13, 14, 140639, tzinfo=utc)),
        ),
    ]
