# Generated by Django 3.1.14 on 2022-02-17 20:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0027_auto_20220215_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentbike',
            name='date_start',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 17, 20, 43, 22, 473184, tzinfo=utc)),
        ),
    ]
