# Generated by Django 3.1.14 on 2022-02-19 18:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0028_auto_20220217_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentbike',
            name='date_start',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 19, 18, 29, 39, 548798, tzinfo=utc)),
        ),
    ]
