# Generated by Django 3.1.14 on 2022-02-20 18:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0031_auto_20220220_1802'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bike',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='bike',
            name='longitude',
        ),
        migrations.AlterField(
            model_name='rentbike',
            name='date_start',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 20, 18, 39, 43, 185735, tzinfo=utc)),
        ),
    ]
