# Generated by Django 3.1.14 on 2022-02-22 11:22

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0021_auto_20220220_1802'),
        ('profiles', '0003_profile_rentactive'),
        ('bikes', '0032_auto_20220220_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentbike',
            name='date_start',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 22, 11, 22, 23, 357637, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='Incidence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default='Incidencia Bici', max_length=600)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=200)),
                ('station', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidence_station', to='stations.station')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incidence_user', to='profiles.profile')),
            ],
        ),
    ]
