# Generated by Django 3.1.14 on 2022-02-22 11:39

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0033_auto_20220222_1122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incidence',
            name='station',
        ),
        migrations.AddField(
            model_name='incidence',
            name='bike',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incidence_bike', to='bikes.bike'),
        ),
        migrations.AlterField(
            model_name='rentbike',
            name='date_start',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 22, 11, 39, 9, 219529, tzinfo=utc)),
        ),
    ]
