# Generated by Django 3.1.14 on 2022-02-22 12:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0034_auto_20220222_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidence',
            name='status',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='rentbike',
            name='date_start',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 22, 12, 15, 6, 112581, tzinfo=utc)),
        ),
    ]
