# Generated by Django 3.1.14 on 2022-11-11 17:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0036_auto_20220223_0915'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bike',
            name='station',
        ),
        migrations.AlterField(
            model_name='rentbike',
            name='date_start',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 11, 17, 22, 51, 284814, tzinfo=utc)),
        ),
    ]
