# Generated by Django 3.1.14 on 2022-11-11 17:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0037_auto_20221111_1722'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bike',
            name='slot',
        ),
        migrations.AlterField(
            model_name='rentbike',
            name='date_start',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 11, 17, 26, 21, 657085, tzinfo=utc)),
        ),
    ]
