# Generated by Django 3.1.14 on 2022-11-11 18:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0038_auto_20221111_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentbike',
            name='date_start',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 11, 18, 24, 26, 842449, tzinfo=utc)),
        ),
    ]
