# Generated by Django 3.1.14 on 2022-11-13 18:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0039_auto_20221111_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidence',
            name='checked',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='rentbike',
            name='date_start',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 13, 18, 47, 41, 876540, tzinfo=utc)),
        ),
    ]
