# Generated by Django 3.1.14 on 2022-11-19 09:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0040_auto_20221113_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentbike',
            name='date_start',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 19, 9, 15, 41, 281001, tzinfo=utc)),
        ),
    ]
